### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by lyderic** [yegor256/kdpcover#11]
I am trying to compile this very simple cover to test this package:

```
$ cat jane.tex
\documentclass[pages=442,6x9]{kdpcover}
\begin{document}
\putSpine{Jane - Un roman comme il faut}
\putTitle{Jane}
\putAuthor{Georges Minesson}
\end{document}
```

Notes:

- I installed texlive as detailed here: https://tug.org/texlive/quickinstall.html
- kdpcover was installed by tlmgr
- I ran 'tlmg update --all' before compiling

Here is the command I ran and the (abbreviated) output (I also attach jane.log):

```
$ pdflatex jane.tex
[...]
(/usr/local/texlive/2022/texmf-dist/tex/latex/microtype/microtype.cfg

! LaTeX Error: The font size command \normalsize is not defined:
               there is probably something wrong with the class file.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.75    }
```

Many thanks for looking at this!

L.

[jane.log](https://github.com/yegor256/kdpcover/files/10095985/jane.log)

**Comment by yegor256** [comment]
@lyderic it was a bug, sorry. Now it's [fixed](https://github.com/yegor256/kdpcover/issues/12), Try version 0.5.0. just do:

```git
$ tlmgr update kdpcover
```

**Comment by lyderic** [comment]
Many thanks Yegor. I confirm it's working now.
L.
